package com.fajri.strayver.util

object Route {
    const val SPLASH= "Splash"
    const val ONBOARD= "Onboarding"
    const val REGISTER= "Register"
    const val LOGIN= "Login"
    const val MEMBER_HOME= "MemberHome"
    const val ARTIKEL_DETAIL= "ArtikelDetail"
    const val MEMBER_DONASI= "MemberDonasi"
    const val DETAIL_DONASI= "DetailDonasi"
    const val KIRIM_DONASI= "KirimDonasi"
    const val MEMBER_RIWAYAT= "MemberRiwayat"
    const val DETAIL_RIWAYAT= "DetailRiwayat"
    const val MEMBER_PROFIL= "MemberProfil"
    const val MEMBER_EDIT_PROFIL= "MemberEditProfil"
    const val LUPASANDI= "LupaSandi"
    const val RELAWAN_HOME= "RelawanHome"
    const val RELAWAN_DONASI= "RelawanDonasi"
    const val TAMBAH_DONASI= "TambahDonasi"
    const val RELAWAN_TRANSAKSI= "RelawanTransaksi"
    const val DETAIL_TRANSAKSI= "DetailTransaksi"
    const val RELAWAN_PROFIL= "RelawanProfil"
    const val BUAT_PROYEK= "BuatProyek"
}